import { ClothingItem } from '../types';

export const STYLE_OPTIONS = [
  'Y2K',
  'Streetwear',
  'Minimalist',
  'Boho',
  'Preppy',
  'Vintage',
  'Chic',
  'Casual',
  'Sporty',
  'Punk',
  'Scandi',
  'Corporate',
  'Grunge',
  'Maximalist',
  'Clean Girl',
  'Coquette',
  'Edgy',
  'Tomboy',
  'Trendy',
  'Elegant',
  'Parisian',
  'Old Money',
  'Flashy',
  'Retro',
  'Indie',
] as const;

export interface AvatarPreset {
  id: string;
  name: string;
  gender: 'Female' | 'Male';
  url: string;
}

export const SAMPLE_AVATARS: AvatarPreset[] = [
  {
    id: 'avatar-female-1',
    name: 'Selin (Casual Chic)',
    gender: 'Female',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'avatar-female-2',
    name: 'Maya (Minimalist)',
    gender: 'Female',
    url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'avatar-male-1',
    name: 'Kaan (Modern Streetwear)',
    gender: 'Male',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'avatar-male-2',
    name: 'Leo (Classic Clean)',
    gender: 'Male',
    url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
  },
];

export const STARTER_CLOTHES: ClothingItem[] = [
  {
    id: 'item-top-1',
    category: 'Tops',
    subcategory: 'Ribbed Crop Knit',
    color: 'Ivory Cream',
    pattern: 'Solid',
    style: 'Clean Girl',
    season: 'All Season',
    occasion: 'Casual',
    image_url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-top-2',
    category: 'Tops',
    subcategory: 'Oversized Poplin Shirt',
    color: 'Sky Blue',
    pattern: 'Solid',
    style: 'Old Money',
    season: 'Spring/Fall',
    occasion: 'Work',
    image_url: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-top-3',
    category: 'Tops',
    subcategory: 'Relaxed Graphic Tee',
    color: 'Vintage White',
    pattern: 'Graphic',
    style: 'Streetwear',
    season: 'Summer',
    occasion: 'Casual',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-bottom-1',
    category: 'Bottoms',
    subcategory: 'High-Waist Wide Leg Trousers',
    color: 'Camel / Beige',
    pattern: 'Solid',
    style: 'Parisian',
    season: 'All Season',
    occasion: 'Work',
    image_url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-bottom-2',
    category: 'Bottoms',
    subcategory: 'Straight Cut Raw Denim Jeans',
    color: 'Indigo Blue',
    pattern: 'Solid',
    style: 'Casual',
    season: 'All Season',
    occasion: 'Casual',
    image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-bottom-3',
    category: 'Bottoms',
    subcategory: 'Pleated Tennis Skirt',
    color: 'Chalk White',
    pattern: 'Pleated',
    style: 'Preppy',
    season: 'Summer',
    occasion: 'Casual',
    image_url: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-outerwear-1',
    category: 'Outerwear',
    subcategory: 'Structured Wool Blazer',
    color: 'Charcoal Black',
    pattern: 'Solid',
    style: 'Corporate',
    season: 'Winter',
    occasion: 'Work',
    image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-shoes-1',
    category: 'Shoes',
    subcategory: 'Classic Leather Sneakers',
    color: 'Triple White',
    pattern: 'Solid',
    style: 'Minimalist',
    season: 'All Season',
    occasion: 'Casual',
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'item-dress-1',
    category: 'Dresses',
    subcategory: 'Silk Slip Midi Dress',
    color: 'Emerald Green',
    pattern: 'Solid',
    style: 'Elegant',
    season: 'Summer',
    occasion: 'Night Out',
    image_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
  },
];
